/* eslint-disable max-lines */
/*
 * EXPORTS
 */
module.exports = {
  'rules': {
    'prettier/prettier': 'off',
    'indent': ['error', 2],
    'strict': ['error', 'global'],
    'semi': ['error', 'never'],
    'no-extra-semi': 'off',
    'no-trailing-spaces': 'error',
    'brace-style': ['error', '1tbs', { 'allowSingleLine': true }],
    'padded-blocks': ['error', 'never'],
    'no-return-assign': 'off',
    'no-multiple-empty-lines': 'off',
    'no-var': 'error',
    'one-var': ['error', { 'let': 'always', 'const': 'never' }],
    'no-unexpected-multiline': 'off',
    'no-tabs': ['error', { 'allowIndentationTabs': true }],
    'no-unreachable': 'error',
    'no-await-in-loop': 'error',
    'no-compare-neg-zero': 'error',
    'no-console': 'error',
    'no-constant-condition': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-dupe-args': 'error',
    'no-dupe-else-if': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-empty': 'error',
    'no-empty-character-class': 'error',
    'no-ex-assign': 'error',
    'no-extra-boolean-cast': 'error',
    'no-extra-parens': 'off',
    'no-func-assign': 'error',
    'no-import-assign': 'error',
    'no-inner-declarations': 'error',
    'no-invalid-regexp': 'error',
    'no-irregular-whitespace': 'error',
    'no-misleading-character-class': 'error',
    'no-obj-calls': 'error',
    'no-prototype-builtins': 'off',
    'no-regex-spaces': 'error',
    'no-setter-return': 'error',
    'no-sparse-arrays': 'error',
    'no-template-curly-in-string': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'require-atomic-updates': 'error',
    'use-isnan': 'error',
    'valid-typeof': ['error', { 'requireStringLiterals': true }],
    'accessor-pairs': 'error',
    'array-callback-return': 'error',
    'block-scoped-var': 'error',
    'class-methods-use-this': 'error',
    'complexity': ['error', { 'max': 200 }],
    'consistent-return': 'error',
    'curly': ['error', 'multi-line', 'consistent'],
    'default-case': 'error',
    'default-param-last': 'error',
    'dot-location': 'off',
    'dot-notation': 'error',
    'eqeqeq': 'error',
    'grouped-accessor-pairs': ['error', 'setBeforeGet'],
    'guard-for-in': 'error',
    'max-classes-per-file': ['error', 1],
    'no-alert': 'error',
    'no-caller': 'error',
    'no-case-declarations': 'error',
    'no-constructor-return': 'error',
    'no-div-regex': 'error',
    'no-else-return': ['error', { 'allowElseIf': true }],
    'no-empty-function': 'error',
    'no-empty-pattern': 'error',
    'no-eq-null': 'error',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-extra-label': 'error',
    'no-fallthrough': 'error',
    'no-floating-decimal': 'error',
    'no-global-assign': 'error',
    'no-implicit-coercion': ['error', { 'boolean': true }],
    'no-implicit-globals': 'error',
    'no-implied-eval': 'error',
    'no-invalid-this': 'error',
    'no-iterator': 'error',
    'no-labels': 'error',
    'no-lone-blocks': 'error',
    'no-loop-func': 'error',
    'no-magic-numbers': 'off',
    'no-multi-spaces': 'error',
    'no-multi-str': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-wrappers': 'error',
    'no-octal': 'error',
    'no-octal-escape': 'error',
    'no-param-reassign': 'off',
    'no-proto': 'error',
    'no-redeclare': 'error',
    'no-return-await': 'error',
    'no-script-url': 'error',
    'no-self-assign': 'error',
    'no-self-compare': 'error',
    'no-sequences': 'off',
    'no-throw-literal': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-unused-expressions': [
      'error',
      {
        'allowShortCircuit': true,
        'allowTernary': true,
        'allowTaggedTemplates': true
      }
    ],
    'no-unused-labels': 'error',
    'no-useless-call': 'error',
    'no-useless-catch': 'error',
    'no-useless-concat': 'error',
    'no-useless-escape': 'error',
    'no-useless-return': 'error',
    'no-void': 'off',
    'no-warning-comments': 'error',
    'no-with': 'error',
    'prefer-named-capture-group': 'off',
    'prefer-promise-reject-errors': 'error',
    'prefer-regex-literals': 'error',
    'radix': 'error',
    'require-await': 'error',
    'require-unicode-regexp': 'error',
    'vars-on-top': 'error',
    'wrap-iife': 'off',
    'yoda': ['error', 'always'],
    'init-declarations': ['error', 'never'],
    'no-delete-var': 'error',
    'no-label-var': 'error',
    'no-shadow': 'error',
    'no-shadow-restricted-names': 'error',
    'no-undef': 'error',
    'no-undef-init': 'error',
    'no-undefined': 'error',
    'no-unused-vars': 'error',
    'no-use-before-define': 'error',
    'callback-return': 'error',
    'global-require': 'off',
    'handle-callback-err': 'error',
    'no-buffer-constructor': 'error',
    'no-mixed-requires': ['error', { 'allowCall': true }],
    'no-new-require': 'error',
    'no-path-concat': 'error',
    'no-process-env': 'off',
    'no-process-exit': 'error',
    'no-restricted-modules': 'off',
    'no-sync': 'error',
    'comma-dangle': ['error', 'never'],
    'quote-props': ['error', 'always'],
    'semi-spacing': 'off',
    'space-before-function-paren': 'off',
    'keyword-spacing': ['error', { 'before': true, 'after': true }],
    'object-curly-spacing': ['error', 'always'],
    'array-bracket-spacing': ['error', 'never'],
    'spaced-comment': ['error', 'always'],
    'func-call-spacing': ['error', 'never'],
    'padding-line-between-statements': [
      'error',
      { 'blankLine': 'always', 'prev': '*', 'next': 'return' },
      { 'blankLine': 'always', 'prev': 'return', 'next': '*' },
      { 'blankLine': 'always', 'prev': '*', 'next': 'break' },
      { 'blankLine': 'always', 'prev': 'directive', 'next': '*' },
      { 'blankLine': 'always', 'prev': '*', 'next': 'switch' },
      { 'blankLine': 'always', 'prev': 'switch', 'next': '*' },
      { 'blankLine': 'always', 'prev': '*', 'next': 'throw' },
      { 'blankLine': 'always', 'prev': 'try', 'next': '*' },
      { 'blankLine': 'always', 'prev': 'var', 'next': '*' },
      { 'blankLine': 'always', 'prev': '*', 'next': 'while' },
      { 'blankLine': 'always', 'prev': 'while', 'next': '*' },
      { 'blankLine': 'always', 'prev': 'let', 'next': '*' },
      { 'blankLine': 'always', 'prev': 'iife', 'next': '*' },
      { 'blankLine': 'always', 'prev': 'function', 'next': '*' },
      { 'blankLine': 'always', 'prev': '*', 'next': 'function' },
      { 'blankLine': 'always', 'prev': 'for', 'next': '*' },
      { 'blankLine': 'always', 'prev': '*', 'next': 'for' },
      { 'blankLine': 'always', 'prev': '*', 'next': 'export' },
      { 'blankLine': 'never', 'prev': 'export', 'next': 'export' },
      { 'blankLine': 'always', 'prev': '*', 'next': 'empty' },
      { 'blankLine': 'always', 'prev': '*', 'next': 'do' },
      { 'blankLine': 'always', 'prev': 'default', 'next': '*' },
      { 'blankLine': 'always', 'prev': '*', 'next': 'debugger' },
      { 'blankLine': 'always', 'prev': 'debugger', 'next': '*' },
      { 'blankLine': 'always', 'prev': '*', 'next': 'debugger' },
      { 'blankLine': 'always', 'prev': 'class', 'next': '*' },
      { 'blankLine': 'always', 'prev': '*', 'next': 'class' },
      { 'blankLine': 'never', 'prev': 'class', 'next': 'class' },
      { 'blankLine': 'always', 'prev': 'cjs-import', 'next': '*' },
      { 'blankLine': 'always', 'prev': '*', 'next': 'cjs-export' },
      { 'blankLine': 'never', 'prev': 'cjs-import', 'next': 'cjs-import' },
      { 'blankLine': 'never', 'prev': 'cjs-export', 'next': 'cjs-export' }
    ],
    'arrow-body-style': ['error', 'as-needed'],
    'arrow-parens': [2, 'as-needed'],
    'no-confusing-arrow': 'off',
    'arrow-spacing': ['error', { 'before': true, 'after': true }],
    'constructor-super': 'error',
    'generator-star-spacing': ['error', { 'before': true, 'after': true }],
    'no-class-assign': 'error',
    'no-const-assign': 'error',
    'no-dupe-class-members': 'error',
    'no-duplicate-imports': 'error',
    'no-new-symbol': 'error',
    'no-restricted-imports': [
      'error',
      'assert',
      'crypto',
      'dgram',
      'domain',
      'freelist',
      'http',
      'https',
      'module',
      'punycode',
      'readline',
      'repl',
      'smalloc',
      'string_decoder',
      'sys',
      'timers',
      'tracing',
      'tty',
      'vm',
      'zlib'
    ],
    'no-this-before-super': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-constructor': 'error',
    'no-useless-rename': 'error',
    'object-shorthand': [
      'error',
      'always',
      {
        'avoidExplicitReturnArrows': true,
        'ignoreConstructors': true,
        'avoidQuotes': true
      }
    ],
    'prefer-arrow-callback': ['error', { 'allowNamedFunctions': true, 'allowUnboundThis': false }],
    'prefer-const': 'error',
    'prefer-numeric-literals': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'require-yield': 'off',
    'rest-spread-spacing': ['error', 'never'],
    'symbol-description': 'error',
    'template-curly-spacing': ['error', 'never'],
    'yield-star-spacing': ['error', 'before'],
    'sort-imports': [
      'error',
      {
        'ignoreCase': true,
        'ignoreDeclarationSort': true,
        'ignoreMemberSort': false
      }
    ],
    'array-bracket-newline': ['error', { 'multiline': true, 'minItems': 5 }],
    'array-element-newline': ['error', { 'multiline': true, 'minItems': 5 }],
    'block-spacing': ['error', 'always'],
    'camelcase': 'off',
    'capitalized-comments': ['error', 'always'],
    'comma-spacing': ['error', { 'before': false, 'after': true }],
    'comma-style': ['error', 'last'],
    'computed-property-spacing': ['error', 'never', { 'enforceForClassMembers': true }],
    'consistent-this': ['error', '_this_'],
    'eol-last': ['error', 'always'],
    'func-name-matching': [
      'error',
      'always',
      {
        'considerPropertyDescriptor': true,
        'includeCommonJSModuleExports': true
      }
    ],
    'func-names': ['error', 'as-needed'],
    'func-style': ['error', 'declaration', { 'allowArrowFunctions': true }],
    'function-paren-newline': ['error', 'consistent'],
    'id-blacklist': ['error', 'with', 'eval'],
    'id-length': 'off',
    'implicit-arrow-linebreak': 'off',
    'jsx-quotes': ['error', 'prefer-single'],
    'quotes': [
      'error',
      'single',
      {
        'avoidEscape': true,
        'allowTemplateLiterals': true
      }
    ],
    'key-spacing': ['error', { 'mode': 'strict' }],
    'line-comment-position': ['off'],
    'linebreak-style': 'error',
    'function-call-argument-newline': ['error', 'consistent'],
    'lines-around-comment': [
      'error',
      {
        'beforeLineComment': false,
        'allowBlockEnd': false,
        'allowClassStart': true,
        'allowClassEnd': false,
        'allowObjectStart': true,
        'allowObjectEnd': false,
        'allowArrayStart': true,
        'allowArrayEnd': false,
        'beforeBlockComment': false
      }
    ],
    'lines-between-class-members': 'off',
    'max-depth': ['error', 11],
    'max-len': [
      'error',
      {
        'code': 1000,
        'ignoreTrailingComments': true,
        'ignoreUrls': true,
        'ignoreTemplateLiterals': true,
        'ignoreStrings': true,
        'ignoreRegExpLiterals': true
      }
    ],
    'max-lines': ['error', { 'max': 1600, 'skipBlankLines': true }],
    'max-lines-per-function': ['error', { 'max': 1000, 'skipComments': true, 'IIFEs': true, 'skipBlankLines': true }],
    'max-nested-callbacks': ['error', 5],
    'max-params': ['error', 10],
    'max-statements': ['error', 300],
    'max-statements-per-line': ['error', { 'max': 7 }],
    'multiline-comment-style': 'error',
    'multiline-ternary': 'off',
    'new-cap': ['error', { 'newIsCap': true, 'capIsNew': false, 'properties': true }],
    'new-parens': 'off',
    'newline-per-chained-call': ['error', { 'ignoreChainWithDepth': 5 }],
    'no-array-constructor': 'error',
    'no-bitwise': 'off',
    'no-continue': 'off',
    'no-inline-comments': 'off',
    'no-lonely-if': 'error',
    'no-mixed-operators': 'error',
    'no-mixed-spaces-and-tabs': ['error', 'smart-tabs'],
    'no-multi-assign': 'error',
    'no-negated-condition': 'error',
    'no-nested-ternary': 'off',
    'no-new-object': 'error',
    'no-plusplus': 'off',
    'no-restricted-syntax': ['error', 'WithStatement'],
    'no-ternary': 'off',
    'no-underscore-dangle': ['off'],
    'no-unneeded-ternary': 'error',
    'no-whitespace-before-property': 'error',
    'nonblock-statement-body-position': ['error', 'beside'],
    'object-curly-newline': ['error', { 'consistent': true }],
    'object-property-newline': ['error', { 'allowAllPropertiesOnSameLine': true }],
    'one-var-declaration-per-line': ['error', 'initializations'],
    'operator-assignment': ['error', 'always'],
    'operator-linebreak': ['error', 'none'],
    'prefer-exponentiation-operator': 'error',
    'prefer-object-spread': 'error',
    'semi-style': 'off',
    'sort-keys': 'off',
    'sort-vars': 'error',
    'space-before-blocks': ['error', { 'functions': 'always', 'keywords': 'always', 'classes': 'always' }],
    'space-in-parens': ['error', 'never'],
    'space-infix-ops': 'error',
    'space-unary-ops': ['error', { 'words': true, 'nonwords': false }],
    'switch-colon-spacing': ['error', { 'after': true, 'before': false }],
    'template-tag-spacing': ['error', 'never'],
    'unicode-bom': 'error',
    'wrap-regex': 'error',
    'id-match': 'off'
  },
  'languageOptions': {
    'globals': {
      'Map': false,
      'Promise': false,
      'Set': false,
      'Enum': false,
      'ACCOUNT_TYPE': false,
      'SMS_STATUS': false,
      'WORKING_ENV': false,
      'CONFIG_RC': false,
      'REGISTERED_DELIVERY': false,
      'module': false,
      'global': false,
      'require': false,
      '__dirname': false,
      'process': false,
      'CUSTOMER_TYPE': false,
      'BILLING_PERIOD': false,
      'JSON': false,
      'Buffer': false,
      'String': false,
      'Number': false,
      'isNaN': false,
      'parseInt': false,
      'parseFloat': false,
      'Date': false,
      'Array': false,
      'Proxy': false,
      'Object': false,
      'Boolean': false,
      'Error': false,
      'RegExp': false,
      'Function': false,
      'Symbol': false,
      'BigInt': false,
      'Math': false,
      'console': false,
      'setTimeout': false,
      'setInterval': false,
      'clearTimeout': false,
      'clearInterval': false
    }
  }
}
